//-----------------------------------------------------------------------
// <copyright file=" t_agent_store.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_agent_store.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_agent_store Entity Model
    /// </summary>    
    [Serializable]
    public class t_agent_store
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 代理商Id
        /// </summary>
        public int AgentId { get; set; }
    
        /// <summary>
        /// 门店Id
        /// </summary>
        public int StoreId { get; set; }
    }
}
