//-----------------------------------------------------------------------
// <copyright file=" t_bannerimage.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_bannerimage.cs
// * history : Created by T4 2018-07-20 13:25:36 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_bannerimage Entity Model
    /// </summary>    
    [Serializable]
    public class t_bannerimage
    {
        public int ID { get; set; }

        public string BannerTitle { get; set; }
    
        public string ImgUrl { get; set; }
 
        public int ClickStatus { get; set; }

        public string ClickTrunOnUrl { get; set; }

        public DateTime UpOnLineTime { get; set; }

        public DateTime DownOnLimeTime { get; set; }

        public int IsDeleted { get; set; }

        public long DeleterUserId { get; set; }

        public DateTime LastModificationTime { get; set; }

        public long LastModifierUserId { get; set; }

        public DateTime CreationTime { get; set; }

        public long CreatorUserId { get; set; }
    }
}
