//-----------------------------------------------------------------------
// <copyright file=" t_customer.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_customer.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_customer Entity Model
    /// </summary>    
    [Serializable]
    public class t_customer
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 客户类型（0:自动；1：服务员手动添加）
        /// </summary>
        public int CustomerType { get; set; }
    
        /// <summary>
        /// 真实姓名
        /// </summary>
        public string TrueName { get; set; }

        /// <summary>
        /// 昵称
        /// </summary>
        public string Nickname { get; set; }

        /// <summary>
        /// 性别 (0：未知、1：男、2：女)
        /// </summary>
        public int Gender { get; set; }

        /// <summary>
        /// 头像链接
        /// </summary>
        public string AvatarUrl { get; set; }

        /// <summary>
        /// 手机号码
        /// </summary>
        public string PhoneNumber { get; set; }

        /// <summary>
        /// 用户微信唯一标识
        /// </summary>
        public string OpenId { get; set; }

        /// <summary>
        /// 微信开放平台唯一标识
        /// </summary>
        public string UnionId { get; set; }

        /// <summary>
        /// 小程序的 appid
        /// </summary>
        public string AppId { get; set; }

        /// <summary>
        /// 所在市
        /// </summary>
        public string City { get; set; }

        /// <summary>
        /// 所在省
        /// </summary>
        public string Province { get; set; }

        /// <summary>
        /// 所在国家
        /// </summary>
        public string Country { get; set; }

        /// <summary>
        /// 籍贯
        /// </summary>
        public string NativePlace { get; set; }

        /// <summary>
        /// 身高
        /// </summary>
        public float Height { get; set; }

        /// <summary>
        /// 生日
        /// </summary>
        public DateTime? Birthday { get; set; }

        /// <summary>
        /// 注册时间
        /// </summary>
        public DateTime RegisterTime { get; set; }

        /// <summary>
        /// 密码
        /// </summary>
        public string PassWord { get; set; }

        /// <summary>
        /// 微信号
        /// </summary>
        public string Wechat { get; set; }
        
        /// <summary>
        /// 备注（服务员手动添加客户信息）
        /// </summary>
        public string Remark { get; set; }
    
        /// <summary>
        /// 删除标志（0：未删除 1：已删除）
        /// </summary>
        public int IsDeleted { get; set; }
    
        /// <summary>
        /// 删除用户Id
        /// </summary>
        public long DeleterUserId { get; set; }
    
        /// <summary>
        /// 最后编辑时间
        /// </summary>
        public DateTime LastModificationTime { get; set; }
    
        /// <summary>
        /// 最后编辑用户Id
        /// </summary>
        public long LastModifierUserId { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }
    
        /// <summary>
        /// 创建用户Id
        /// </summary>
        public long CreatorUserId { get; set; }
    }
}
