//-----------------------------------------------------------------------
// <copyright file=" t_message.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_message.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_message Entity Model
    /// </summary>    
    [Serializable]
    public class t_message
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 消息类型（0：系统消息；1：聊天消息）
        /// </summary>
        public int MessageType { get; set; }
    
        /// <summary>
        /// 门店Id
        /// </summary>
        public int StoreId { get; set; }

        /// <summary>
        /// 发送消息者OpenId
        /// </summary>
        public string SendOpenId { get; set; }

        /// <summary>
        /// 发送消息者Id
        /// </summary>
        public int SendUserId { get; set; }

        /// <summary>
        /// 接受消息者OpenId
        /// </summary>
        public string AcceptOpenId { get; set; }

        /// <summary>
        /// 接受消息者Id
        /// </summary>
        public int AcceptUserId { get; set; }
    
        /// <summary>
        /// 内容
        /// </summary>
        public string Content { get; set; }
    
        /// <summary>
        /// 发送时间
        /// </summary>
        public DateTime SendTime { get; set; }
    
        /// <summary>
        /// 状态（0：未读 1：已读）
        /// </summary>
        public int State { get; set; }
    
        /// <summary>
        /// 删除标志（0：未删除 1：已删除）
        /// </summary>
        public int IsDeleted { get; set; }
    
        /// <summary>
        /// 删除用户Id
        /// </summary>
        public long DeleterUserId { get; set; }
    
        /// <summary>
        /// 最后编辑时间
        /// </summary>
        public DateTime LastModificationTime { get; set; }
    
        /// <summary>
        /// 最后编辑用户Id
        /// </summary>
        public long LastModifierUserId { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }
    
        /// <summary>
        /// 创建用户Id
        /// </summary>
        public long CreatorUserId { get; set; }
    }
}
