//-----------------------------------------------------------------------
// <copyright file=" t_payment.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_payment.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_payment Entity Model
    /// </summary>    
    [Serializable]
    public class t_payment
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 支付订单号
        /// </summary>
        public string PaymentNo { get; set; }
    
        /// <summary>
        /// 支付人Id
        /// </summary>
        public int CustomerId { get; set; }
    
        /// <summary>
        /// 支付商品Id
        /// </summary>
        public int GoodsId { get; set; }
    
        /// <summary>
        /// 支付时间
        /// </summary>
        public DateTime PaymentTime { get; set; }
    
        /// <summary>
        /// 支付金额
        /// </summary>
        public decimal Money { get; set; }
    
        /// <summary>
        /// 支付状态（0：失败；1：成功）
        /// </summary>
        public int State { get; set; }
    }
}
