//-----------------------------------------------------------------------
// <copyright file=" t_reward_distribution.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_reward_distribution.cs
// * history : Created by T4 2018-07-11 11:00:23 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_reward_distribution Entity Model
    /// </summary>    
    [Serializable]
    public class t_reward_distribution
    {
        /// <summary>
        /// 
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 方案名称
        /// </summary>
        public string DistributionName { get; set; }
    
        /// <summary>
        /// 平台分配比例
        /// </summary>
        public decimal PlatformRatio { get; set; }
    
        /// <summary>
        /// 代理商分配比例
        /// </summary>
        public decimal AgentRatio { get; set; }
    
        /// <summary>
        /// 门店分配比例
        /// </summary>
        public decimal StoreRatio { get; set; }
    
        /// <summary>
        /// 服务人员分配比例
        /// </summary>
        public decimal BusinessRatio { get; set; }
    
        /// <summary>
        /// 是否默认方案（0：不是1：是）
        /// </summary>
        public int IsDefault { get; set; }
    
        /// <summary>
        /// 是否当前使用方案（0：不是1：是）
        /// </summary>
        public int IsUse { get; set; }
    
        /// <summary>
        /// 删除标志（0：未删除 1：已删除）
        /// </summary>
        public int IsDeleted { get; set; }
    
        /// <summary>
        /// 删除用户Id
        /// </summary>
        public long DeleterUserId { get; set; }
    
        /// <summary>
        /// 最后编辑时间
        /// </summary>
        public DateTime LastModificationTime { get; set; }
    
        /// <summary>
        /// 最后编辑用户Id
        /// </summary>
        public long LastModifierUserId { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }
    
        /// <summary>
        /// 创建用户Id
        /// </summary>
        public long CreatorUserId { get; set; }
    }
}
