//-----------------------------------------------------------------------
// <copyright file=" t_reward_detail.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_reward_detail.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_reward_detail Entity Model
    /// </summary>    
    [Serializable]
    public class t_reward_detail
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 打赏Id
        /// </summary>
        public int RewardId { get; set; }
    
        /// <summary>
        /// 受益人OpenId
        /// </summary>
        public string OpenrId { get; set; }
    
        /// <summary>
        /// 分配比例
        /// </summary>
        public float DistributionRatio { get; set; }
    
        /// <summary>
        /// 用户类型(0：平台；1：代理商；2：门店；3：服务员)
        /// </summary>
        public int UserType { get; set; }
    
        /// <summary>
        /// 打赏金额
        /// </summary>
        public decimal RewardMoney { get; set; }
    
        /// <summary>
        /// 受益金额
        /// </summary>
        public decimal BenefitMoney { get; set; }
    }
}
