//-----------------------------------------------------------------------
// <copyright file=" t_reward_goods.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_reward_goods.cs
// * history : Created by T4 2018-07-11 11:00:23 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_reward_goods Entity Model
    /// </summary>    
    [Serializable]
    public class t_reward_goods
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 打赏规则Id
        /// </summary>
        public int PlanId { get; set; }
    
        /// <summary>
        /// 商品图片地址
        /// </summary>
        public string GoodsImgUrl { get; set; }
    
        /// <summary>
        /// 商品名称
        /// </summary>
        public string GoodsName { get; set; }
    
        /// <summary>
        /// 商品金额
        /// </summary>
        public decimal Money { get; set; }
    
        /// <summary>
        /// 删除标志（0：未删除 1：已删除）
        /// </summary>
        public int IsDeleted { get; set; }
    
        /// <summary>
        /// 删除用户Id
        /// </summary>
        public long DeleterUserId { get; set; }
    
        /// <summary>
        /// 最后编辑时间
        /// </summary>
        public DateTime LastModificationTime { get; set; }
    
        /// <summary>
        /// 最后编辑用户Id
        /// </summary>
        public long LastModifierUserId { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }
    
        /// <summary>
        /// 创建用户Id
        /// </summary>
        public long CreatorUserId { get; set; }
    }
}
