//-----------------------------------------------------------------------
// <copyright file=" t_store.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_store.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_store Entity Model
    /// </summary>    
    [Serializable]
    public class t_store
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 申请人OpenId
        /// </summary>
        public string ApplyOpenId { get; set; }
    
        /// <summary>
        /// 门店名称
        /// </summary>
        public string StoreName { get; set; }
    
        /// <summary>
        /// 门店电话
        /// </summary>
        public string PhoneNumber { get; set; }
    
        /// <summary>
        /// 门店图片链接
        /// </summary>
        public string StoreImgUrl { get; set; }
    
        /// <summary>
        /// 所在区
        /// </summary>
        public string Area { get; set; }
    
        /// <summary>
        /// 所在市
        /// </summary>
        public string City { get; set; }
    
        /// <summary>
        /// 所在省
        /// </summary>
        public string Province { get; set; }
    
        /// <summary>
        /// 详细地址
        /// </summary>
        public string Address { get; set; }
    
        /// <summary>
        /// 状态（0：待审核 1：启用 2：禁用）
        /// </summary>
        public int State { get; set; }
    
        /// <summary>
        /// 门店评分
        /// </summary>
        public float Score { get; set; }
    
        /// <summary>
        /// 删除标志（0：未删除 1：已删除）
        /// </summary>
        public int IsDeleted { get; set; }
    
        /// <summary>
        /// 删除用户Id
        /// </summary>
        public long DeleterUserId { get; set; }
    
        /// <summary>
        /// 最后编辑时间
        /// </summary>
        public DateTime LastModificationTime { get; set; }
    
        /// <summary>
        /// 最后编辑用户Id
        /// </summary>
        public long LastModifierUserId { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }
    }
}
