//-----------------------------------------------------------------------
// <copyright file=" t_store_business.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_store_business.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_store_business Entity Model
    /// </summary>    
    [Serializable]
    public class t_store_business
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }
    
        /// <summary>
        /// 门店Id
        /// </summary>
        public int StoreId { get; set; }
    
        /// <summary>
        /// 商户Id
        /// </summary>
        public int BusinessId { get; set; }

        /// <summary>
        /// 上级用户ID
        /// </summary>
        public int ParentId { get; set; }

        /// <summary>
        /// 角色Id  （0：超级管理员 1：管理员 2：门店经理 3：服务人员）
        /// </summary>
        public int RoleId { get; set; }

        /// <summary>
        /// 状态( 0:启用 1：禁用)
        /// </summary>
        public int State { get; set; }
    }
}
