//-----------------------------------------------------------------------
// <copyright file=" t_wallet.cs" company="LingLong Enterprises">
// * Copyright (C) 2018 LingLong Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: t_wallet.cs
// * history : Created by T4 2018-07-06 23:37:34 
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace LingLong.Model
{
    /// <summary>
    /// t_wallet Entity Model
    /// </summary>    
    [Serializable]
    public class t_wallet
    {
        /// <summary>
        /// ID
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// 门店Id(对于商户来说，不同门店有不同的钱包)
        /// </summary>
        public int StoreId { get; set; }

        /// <summary>
        /// 用户微信唯一标识
        /// </summary>
        public string OpenId { get; set; }
    
        /// <summary>
        /// 余额
        /// </summary>
        public decimal Balance { get; set; }
    
        /// <summary>
        /// 已提取金额
        /// </summary>
        public decimal Withdraw { get; set; }
    
        /// <summary>
        /// 删除标志（0：未删除 1：已删除）
        /// </summary>
        public int IsDeleted { get; set; }
    
        /// <summary>
        /// 删除用户Id
        /// </summary>
        public long DeleterUserId { get; set; }
    
        /// <summary>
        /// 最后编辑时间
        /// </summary>
        public DateTime LastModificationTime { get; set; }
    
        /// <summary>
        /// 最后编辑用户Id
        /// </summary>
        public long LastModifierUserId { get; set; }
    
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreationTime { get; set; }
    
        /// <summary>
        /// 创建用户Id
        /// </summary>
        public long CreatorUserId { get; set; }
    }
}
